# Generated by Django 3.2.4 on 2023-01-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='+255 format', max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
